### ISSUE TITLE
[staging] Users shouldn't be able to post a change explanation without a change

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#1014]
Note that this is a regression.

**Repro**
1. Open an unset attribute's update window.
2. Write an explanation but don't edit the attribute.
3. Publish the update.

**Current**
You'll see the change explanation without an accompanying change in the feed.

**Expected**
You shouldn't be able to post a change explanation at all; clicking the Publish button should trigger an error message.

**Comment by milesmcc** [comment]
So I actually think that this might not be a regression, and rather a long-standing issue with single-select attributes; see the most recent update on https://platform.atlos.org/incidents/YYIYA8.

The issue is that you go from the value being unset, to the value being set (to null); these from Atlos' perspective are different, which explains why there is no error.

In any case, not the expected behavior, so will fix...
