### ISSUE TITLE
Add projects page to onboarding flow

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#503]
[Not a deploy blocker]
On the "Attributes describe incidents." page, let's change the copy that currently describes each default attribute to instead read:

:lock: **Core attributes** like date and geolocation describe essential information about events, so they apply to all incidents.

💡 Every incident comes with several **default attributes** to help you build your own descriptive model.

:pencil2: If the default options don't work for your project, you can create new **custom attributes.**

While you're making these changes, I think we should change "Atlos is an open source commons" to "Atlos is an open source project" on the first page if possible.

**Comment by noah-schechter** [comment]
I considered proposing a new projects page in the onboarding flow but I think we wait until access controls are done to decide what that requires.

**Comment by milesmcc** [comment]
What about "Atlos is an open source platform for visual investigations"?

<img width="525" alt="image" src="https://user-images.githubusercontent.com/3037552/223029248-e82c9dd9-8dbd-46e7-b02f-1cf31f676448.png">

<img width="573" alt="image" src="https://user-images.githubusercontent.com/3037552/223029500-d555a9c5-2f56-4d90-b012-7a43c2c786a1.png">

(Removed the demo attribute display because it wasn't playing nice with the new system. We should do a bigger overhaul of the onboarding flow once projects are done.)

**Comment by milesmcc** [comment]
Reopen as needed
