### ISSUE TITLE
Add code/link option to join projects

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#561]
This may depend on how what pricing model we pursue.

**Comment by noah-schechter** [comment]
This should be similar to the current platform invitation system—the code can also be embedded in the URL.

**Comment by milesmcc** [comment]
There are a couple of functions/design goals I see here:

* Make it so that you can't just add someone to a project; you have to invite them, and they have to accept. This is something that NCC encouraged us to do; you shouldn't be able to clutter someone's Atlos workspace with new projects that they don't want to be a part of.
* Make it easier for people to invite collaborators who are not yet on Atlos to projects.
* Make it easier for us to manage invite codes; the single-code-for-all situation is untenable.

Functionally, here are some things that the system should support:

* Project owners can generate single-use codes that, when clicked, allow the user to 1) sign up for Atlos (if they're not already on the platform) and 2) have the option to be added to a project. (Ideally these codes could be either single use or multiple use; in either case, they should expire after a week. I'm not sure if the expiry should be configurable.)
* We can send single-use invite codes to people to join Atlos, without adding them to a project.

Functionally, here's how I think this should work:

* We modify invite codes so that they are optionally tied to a Project (with a specific access level), can be single-use or multi-use, and have an expiry date.
* We remove the ability to add someone to a project by username.
* Invite codes are less _codes_ and more _links_: You create an invite and send it to someone; they click it and then are able to sign up for Atlos (if they don't already have an account) and join the project. (When on the sign up page, they will be told that they will be added to Project X when they sign up; if they already have an account, they'll see a page where they have the option to accept the invite.)
* When an invite code is acted upon, the person who created the invite will get an email. (E.g., "Noah used your invite code and is now a member of Project X".)

Importantly, invite codes would _not_ be tied to any particular recipient. Open invite codes would be displayed on the Access page for project owners; platform-level Admins would also be able to see and manage projectless invite codes in Adminland. When we move away from an invite code based system for all sign ups, we'll just drop the requirement to have an invite link/code when signing up; the invite system will still be used for adding people to projects.

**Comment by noah-schechter** [comment]
This generally makes a lot of sense. I want to explore several points you made here before we commit to this approach:

> When an invite code is acted upon, the person who created the invite will get an email. (E.g., "Noah used your invite code and is now a member of Project X".)

We've generally (I think for simplicity, not as a design choice) shied away from notifying users about platform events via email. Why should project invite acceptance be any different?    
  <br>
> Tying invitations to recipients who are already on the platform (GitHub style; you add them by entering their username once they've already signed up, and they receive an invitation in-platform). This isn't ideal because an org might not want to have to enter each new member individually; also, it means that we'd still need a separate system for handing platform-level sign ups, whereas I think the system should be unified.

Your point on in-platform project invites being complicated because orgs might not want to add 20 names one at a time makes a lot of sense. I want to clarify your second point here—why should the system be unified? Because that reduces design complexity? Or because it makes sense for the user? I'm interrogating this point only because I imagine we can solve the many-names-at-a-time problem with an in-app invite system if we choose to, and _not_ having an entirely in-app system for sharing data feels a bit odd.

**Comment by milesmcc** [comment]
On emails — the one time we *do* notify people is when they log into their accounts, because that’s a very sensitive/security relevant action. I think someone using your invite code is similarly sensitive, but I do think that just having a notification could also be ok.

On a unified system, it’s because I think that the way you add someone to a project should be the same regardless of whether they’re on Atlos or not; it would be confusing for users if there were two ways to add someone to a project. Google docs can get away with having purely in-platform invites because their identifiers are emails, so they work regardless of whether the invitee already has an account. We do not have that luxury. I don’t think the “here’s a link to join the project” workflow is weird/too foreign; I think this is how a lot of group chat apps work, for example.

**Comment by noah-schechter** [comment]
On emails—I think an in-app notification is sufficient.

On a unified system, this makes sense. Let's do it.
