### ISSUE TITLE
Consider hiding hash information behind an 'expand' button

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#602]
I think it's fantastic we're collecting the hash information, especially the perceptual hash, but I'm not sure if it's sufficiently useful to investigators that it needs to be displayed in the media modal. I'm thinking about how to conserve vertical space so that it's easier to scroll to the next artifact. Perhaps we hide it beyond three dots or another 'Expand' or 'Show More' button.

**Comment by milesmcc** [comment]
I'm not sure I agree. It doesn't use that much vertical height per artifact (just ~2rem) and I think it's important for demonstrating that we do actually have the information. Like, even if we don't expect most investigators to use it, showing them that it's there makes our archival process seem more robust. Maybe there is a third piece of information we can show in the row to round things out a bit more (since it's kind of strange to have 3 then 2 in the row)?

**Comment by milesmcc** [comment]
Or, if we move artifact type elsewhere, we can combine the two types of hashes (sha256 and perceptual) into a single grid item, and thus we have only one row of data
