### ISSUE TITLE
Add the ability to export underlying media

### ISSUE THREAD

**Issue by milesmcc** [atlosdotorg/atlos#719]

**Comment by noah-schechter** [comment]
Spec for this issue:
- Export functionality should permit export across projects—you should be able to export arbitrary searches
- Exports should use a nested folder system, where the export is a folder containing folders (where each folder is an incident) containing folders where each folder is a piece of media) containing files (where each file is an artifact
<img width="316" alt="Screenshot 2023-11-20 at 10 26 36 AM" src="https://github.com/atlosdotorg/atlos/assets/100018299/cb0f91fc-9b37-44dd-8a82-1486643144d2">

- Naming: Each file should be named [Artifact type]_[Source material ID]. For example, for ATL-ABCDEF/1, the viewport screenshot should be named "ViewportScreenshot_ATL-123456-1.png". Note that because this is a filename, I'm proposing we use "-1" instead of the "/1" to indicate the source material's ID.

**Comment by JettChenT** [comment]
Minor issue regarding the second layer media naming scheme of `CIV-ABC123/1` etc. This involves a `/` character, which  would be an invalid name in most unix/linux systems? 
Renamed changed to `/` to `-` for now on #780

**Comment by noah-schechter** [comment]
Closing as the main functionality is now implemented. Track pre-release improvements here: https://github.com/atlosdotorg/atlos/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Full+media+export+%22
